### ISSUE TITLE
Snapshot action is not working

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#122]
## Scenario
1- Run a Blueprint to create a vm (vm1)
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__64a2b0d4:
       name: 'fddc883e'
       dir: '/root/.ssh/'
       passphrase: '64a2b0d4'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__96769cda:
      name: 'be-g8-3.demo.greenitglobe.com'
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJ1Z3ZoYnI4dENtVUFrMHZLTC1KNTNOZnVLdERwIiwiZXhwIjoxNTI2OTEwNzEwLCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJyZWZyZXNoX3Rva2VuIjoiQklvNEU3N3JjY1ZxV3M2S2ctRk9zSksybkR6dyIsInNjb3BlIjpbInVzZXI6YWRtaW4iXSwidXNlcm5hbWUiOiJnaWdfcWFfMSJ9.PiGG0eAqdwIU-o5of8aKibPL4duhbjJO2zOhYf7VFHtyYBjfWvpKh7WvK7rrWMMbA-1eOG070OZ_BYO8Rd8EI9_luYwiYwAzN9rPLpS_CCjjezGbcQ0VJtxR8Lhiz6cj'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__56e1a419:
      groups: ['user']
      email: eb8c827b@test.com
      openvcloud: 96769cda
      provider: itsyouonline
      name: 0a64a4ff
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      openvcloud: 96769cda
      provider: itsyouonline
      name: gig_qa_1

  - github.com/openvcloud/0-templates/account/0.0.1__b0ad413e:
      openvcloud: 96769cda
      name: b6369881

  - github.com/openvcloud/0-templates/vdc/0.0.1__5a3aff86:
      account: b0ad413e
      name: e9d41ee7

  - github.com/openvcloud/0-templates/node/0.0.1__b6908c56:
      vdc: 5a3aff86
      sshKey: 64a2b0d4
      name: 6843aae6

actions:
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/sshkey/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/node/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/openvcloud/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
    actions: ['install']
```
2- Run another one to create a snapshot for vm1
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__64a2b0d4:
       name: 'fddc883e'
       dir: '/root/.ssh/'
       passphrase: '64a2b0d4'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__4316dbb9:
      name: 'be-g8-3.demo.greenitglobe.com'
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJ1Z3ZoYnI4dENtVUFrMHZLTC1KNTNOZnVLdERwIiwiZXhwIjoxNTI2OTEwODEyLCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJyZWZyZXNoX3Rva2VuIjoiTFlkTUhJMDFCQnZISEo5YW92UlAtTFc1MElGcCIsInNjb3BlIjpbInVzZXI6YWRtaW4iXSwidXNlcm5hbWUiOiJnaWdfcWFfMSJ9.TEaLL1KRj4kZibvsXcjojtpw8kMQaNZ-YYaWIT5xOGRX2560gLbFwOchHLMB_1Gm6YuyivofrK0TfRvstJnoYmPgo2376WAfH-oG3iacWALEqaJ5KNHLukmKj_9CaLAV'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      openvcloud: 4316dbb9
      provider: itsyouonline
      name: gig_qa_1

  - github.com/openvcloud/0-templates/account/0.0.1__b0ad413e:
      openvcloud: 96769cda
      name: b6369881

  - github.com/openvcloud/0-templates/vdc/0.0.1__5a3aff86:
      account: b0ad413e
      name: e9d41ee7

  - github.com/openvcloud/0-templates/node/0.0.1__b6908c56:
      vdc: 5a3aff86
      sshKey: 64a2b0d4
      name: 6843aae6

actions:
  - template: github.com/openvcloud/0-templates/node/0.0.1
    actions: ['snapshot']
    service: b6908c56
```

## Actual Result 
Snapshots hasn't been  created on OVC environment
