### ISSUE TITLE
Can't stop or pause a vm (may be it is a problem with all vm actions)

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#126]
## Scenario
1- create account, vdc, and a vm
2- Stop (or pause) this vm using the following blueprint
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__79481b7f:
       name: '79481b7f'
       dir: '/root/.ssh/'
       passphrase: '79481b7f'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__e0411964:
      name: 'be-g8-3.demo.greenitglobe.com'
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJ1Z3ZoYnI4dENtVUFrMHZLTC1KNTNOZnVLdERwIiwiZXhwIjoxNTI4Nzk3MTMwLCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJyZWZyZXNoX3Rva2VuIjoiSVc4X1pLblJQbi1pb0phSThibWdwRmRnd0J3RyIsInNjb3BlIjpbInVzZXI6YWRtaW4iXSwidXNlcm5hbWUiOiJnaWdfcWFfMSJ9.mBnTRQaMlSOvsT89_ldVHxhzdv8GdhO0V3_Z09squFNO00GvYOd9mRM2I07Gwg0uXSWAf6UsuVxKyM63Mhk5FYnv4zzz1clJPJdZN_Efl-26ksMxx04g2iXgztgu4w9N'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      name: gig_qa_1
      openvcloud: e0411964
      provider: itsyouonline

  - github.com/openvcloud/0-templates/account/0.0.1__357c12dc:
      name: cb7b1e51
      openvcloud: a06aac3b

  - github.com/openvcloud/0-templates/vdc/0.0.1__4a8043fe:
      name: cd542111
      account: 357c12dc

  - github.com/openvcloud/0-templates/node/0.0.1__84668f86:
      vdc: 4a8043fe
      name: da40ea67
      sshKey: 689b9bb4

actions:
  - template: github.com/openvcloud/0-templates/node/0.0.1
    actions: ['stop']
    service: 84668f86
```
## Actual result
The vm didn't stop or pause
## Zrobot version
version: development branch
commit 60a521780fd832299fef57d5fae403818d2c6447
