### ISSUE TITLE
A service has been created without defining it in the blueprint 

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#23]
## Scenario 
1- Create a blueprint to create acc1 and vdc1
```
services:
    - github.com/openvcloud/0-templates/sshkey/0.0.1__key2:
        path: '/root/.ssh/id_rsa'
    - github.com/openvcloud/0-templates/openvcloud/0.0.1__be-g8-4:
        address: 'be-g8-4.demo.greenitglobe.com'
        login: 'kheirj@itsyouonline'
        token: '***'
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__kheirj:
        provider: itsyouonline
        email: kheirj@greenitglobe.com
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__bisho:
        provider: itsyouonline
        email: abdelmab@greenitglobe.com
    - github.com/openvcloud/0-templates/account/0.0.1__acc1:
        users:
             - accesstype: CXDRAU
               name: kheirj

    - github.com/openvcloud/0-templates/vdc/0.0.1__azmyvdci3:
        location: be-g8-4
        users:
             - name: bisho
               accesstype: CXDRAU
             # - name: kheirj
             #  accesstype: CXDRAU

actions:
    - template: github.com/openvcloud/0-templates/account/0.0.1
      actions: ['install']

    - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
      actions: ['install']

    - template: github.com/openvcloud/0-templates/vdc/0.0.1
      actions: ['install']

```
2- Change actions to uninstall and run the bp again, acc1 and vdc1 should be uninstalled 
3- Change the account name to acc2 and specify a "service=acc2" in actions section under account , and run the blueprint.

## Actual Result 
acc1 will be created again while it shouldn't be created.
