### ISSUE TITLE
data.yaml is updated with wrong data 

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#26]
1- Run a blueprint to create acctest1 and vdc1
2- Run another blueprint to create acctest2 and vdc1(vdci3) (using acc2)

## Actual Result 
From OVC side: acctest1 is created and vdc1 is under it, then acctest2 is created without any vdc1 under it (which is okay for now )
From zrobot side: The problem is that the vdc1 data is pointing to acctest2 which shouldn't happen
![erer1](https://user-images.githubusercontent.com/15011431/36721818-ac5d9394-1bb4-11e8-9518-2b206d628f08.png)

**Comment by muhamadazmy** [comment]
Can u please post the bp u used, with exact steps

**Comment by john-kheir** [comment]
```
services:
    - github.com/openvcloud/0-templates/sshkey/0.0.1__key2:
        path: '/root/.ssh/id_rsa'
    - github.com/openvcloud/0-templates/openvcloud/0.0.1__be-g8-4:
        address: 'be-g8-4.demo.greenitglobe.com'
        login: 'kheirj@itsyouonline'
        token: '****'
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__kheirj:
        openvcloud: be-g8-4
        provider: itsyouonline
        email: kheirj@greenitglobe.com
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__bisho:
        openvcloud: be-g8-4
        provider: itsyouonline
        email: abdelmab@greenitglobe.com
    - github.com/openvcloud/0-templates/account/0.0.1__acctest1:
        openvcloud: be-g8-4
        users:
             - accesstype: CXDRAU
               name: kheirj

    - github.com/openvcloud/0-templates/vdc/0.0.1__vdci3:
        account: acctest1
        location: be-g8-4
        users:
             - name: bisho
               accesstype: CXDRAU


actions:
    - template: github.com/openvcloud/0-templates/account/0.0.1
      actions: ['install']

    - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
      actions: ['install']

    - template: github.com/openvcloud/0-templates/vdc/0.0.1
      actions: ['install']
```
