### ISSUE TITLE
Creating more than cloud space is not working as expected.. Cloud spaces turn virtual

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#49]
## Scenario
- Run a blueprint to create account and 2 cloud spaces, should succeed
```
services:
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__d49e839b:
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'kheirj@itsyouonline'
      token: '***'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__kheirj:
      provider: itsyouonline
      email: kheirj@greenitglobe.com
      openvcloud: d49e839b
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__80abf47b:
      provider: itsyouonline
      email: abdelmab@greenitglobe.com
      openvcloud: d49e839b

  - github.com/openvcloud/0-templates/account/0.0.1__d7a8f61f:
      openvcloud: d49e839b

  - github.com/openvcloud/0-templates/vdc/0.0.1__b5c053e7:
      location: be-g8-3
      account: d7a8f61f
  - github.com/openvcloud/0-templates/vdc/0.0.1__73777c30:
      location: be-g8-3
      account: d7a8f61f
      users:
         - name: 80abf47b
           accesstype: CXDRAU

actions:
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    actions: ['install']

```

## Actual Result
- Two cloud spaces have been created but they turned virtual.

![cscs22](https://user-images.githubusercontent.com/15011431/37275559-3dbfcbd0-25e8-11e8-82df-777983b40395.png)

## Note
- If i just created one cloud space, it will be deployed, this error happens only when i try to create more than one cloud space.
- Also I'm not sure where is the best place to create this ticket but i created it here anyways.
