### ISSUE TITLE
Can update an account (same issue with vdc) with a user that doesn't exist. 

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#55]
## Scenario
1- Run a blueprint to create an account with existing user.
```
services:
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__87c47d6d:
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: '****'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      provider: itsyouonline
      openvcloud: 87c47d6d

  - github.com/openvcloud/0-templates/account/0.0.1__test33:
      openvcloud: 87c47d6d
      users:
          - name: gig_qa_1
          - accesstype: CXDRAU

actions:
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
    actions: ['install']

```

2- Run the same blueprint with providing user "gig" (which doesn't exist), should throw an error that this user doesn't exist.
```
services:
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__87c47d6d:
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: '****'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      provider: itsyouonline
      openvcloud: 87c47d6d

  - github.com/openvcloud/0-templates/account/0.0.1__test33:
      openvcloud: 87c47d6d
      users:
          - name: gig
          - accesstype: CXDRAU

actions:
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
    actions: ['install']
```

## Actual Result
The blueprint has been executed for the second time with no errors and the data.yaml file for account's service has been updated with a user that doesn't exist

## Note
This update is just happening from the zrobot point of view.. but it didn't happen in the OVC.
