### ISSUE TITLE
Create a vdc throws an error while the vdc has been deployed in the env

### ISSUE THREAD

**Issue by islamTaha12** [openvcloud/0-templates#59]
**Description**
Create a vdc throws an error while the vdc has been deployed in the env

**Blueprint**
```yml
services:
    - github.com/openvcloud/0-templates/openvcloud/0.0.1__myovc:
        location: be-g8-3
        address: 'be-g8-3.demo.greenitglobe.com'
        token: '*************************************************'
    - github.com/openvcloud/0-templates/account/0.0.1__adminDatas:
    - github.com/openvcloud/0-templates/vdc/0.0.1__myspace:
        openvcloud: myovc
        account: adminDatas
actions:
    - actions: ['install']
```

**0-robot Logs**
```python
* Get OpenvCloud client on URL: be-g8-3.demo.greenitglobe.com
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
* Cloudspace is still deploying, checking again in 2 second
[Fri16 17:44] - base.py           :195 :service-936b7a19-2d22-47d3-b16d-7b96d05dcfc6 - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 79, in execute
    self._result = self.func()
  File "/opt/code/github/openvcloud/0-templates/templates/vdc/vdc.py", line 111, in install
    externalnetworkId=externalnetworkId
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Account.py", line 90, in space_get
    return self.space_get(name, location, False)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Account.py", line 74, in space_get
    if space.model['name'] == name and space.model['location'] == location:
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Space.py", line 72, in model
    raise RuntimeError("timeout on getting space info from %s" % self)
RuntimeError: timeout on getting space info from space: myspace (1131)
```

**The Env status**
![image](https://user-images.githubusercontent.com/17981089/37536448-428c1646-2953-11e8-98dd-42e7aaaebb92.png)
