### ISSUE TITLE
A created user didn't take access on a certain machine

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#63]
user: john7989c02@itsyouonline didn't get access to "node1" vm
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__f5a153a5:
       dir: '/root/.ssh/'
       passphrase: 'f5a153a5'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__d022dd06:
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: '**************'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__john7989c02:
      groups: ['user', 'admin']
      email: 0bec78f8@test.com
      openvcloud: d022dd06
      provider: itsyouonline
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      openvcloud: d022dd06
      provider: itsyouonline

  - github.com/openvcloud/0-templates/account/0.0.1__067aa06a:
      openvcloud: d022dd06

  - github.com/openvcloud/0-templates/vdc/0.0.1__0f32af8d:
      account: 067aa06a

  - github.com/openvcloud/0-templates/node/0.0.1__node1:
      vdc: 0f32af8d
      dataDiskSize: 11
      ports:
        - source: 2222
          destination: 22
      bootDiskSize: 12
      users:
        - name: john7989c02
          accesstype: CXDRAU
      sshKey: f5a153a5
  - github.com/openvcloud/0-templates/node/0.0.1__node2:
      vdc: 0f32af8d
      sshKey: f5a153a5

actions:
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/node/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1

```

![scsh](https://user-images.githubusercontent.com/15011431/37601525-e5a9666c-2b92-11e8-80c4-82e6e52c4828.png)
