### ISSUE TITLE
Server was aborted when i tried to run a blueprint to create a vm.

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#76]
## Blueprint
```
services:
    - github.com/openvcloud/0-templates/sshkey/0.0.1__key:
        dir: '/root/.ssh/'
        passphrase: 'tesing'
    - github.com/openvcloud/0-templates/openvcloud/0.0.1__be-g8-3:
        address: 'be-g8-3.demo.greenitglobe.com'
        login: 'kheirj@itsyouonline'
        token: '********'
        location: be-g8-3 
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
        openvcloud: be-g8-3
        provider: itsyouonline
        email: dina.magdy.mohammed+123@gmail.com
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__test99:
        openvcloud: be-g8-3
        provider: itsyouonline
        email: test@greenitglobe.com
    - github.com/openvcloud/0-templates/account/0.0.1__johnacc33:
        openvcloud: be-g8-3
        users:
            - name: kheirj
              accesstype: CXDRAU
    - github.com/openvcloud/0-templates/vdc/0.0.1__azmyvdc:
        account: johnacc33
        location: be-g8-3
        users:
            - name: gig_qa_1
              accesstype: CXDRAU
            - name: test99
              accesstype: CXDRAU
    - github.com/openvcloud/0-templates/node/0.0.1__vmnode:
        users:
          - name: test99
            accesstype: CXDRAU
        bootDiskSize: 17
        sshKey: key
        vdc: azmyvdc
        dataDiskSize: 18
        ports:
           - source: 2222
             destination: 22
           - source: 2233
             destination: 33
actions:
    - template: github.com/openvcloud/0-templates/account/0.0.1
      actions: ['install']

    - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
      actions: ['install']

    - template: github.com/openvcloud/0-templates/vdc/0.0.1
      actions: ['install']

    - template: github.com/openvcloud/0-templates/node/0.0.1
      actions: ['install']

```

## Error
```
[Sun25 08:51] - OVCClient.py      :66  :nts.openvcloud.be-g8-3 - INFO     - Get OpenvCloud client on URL: be-g8-3.demo.greenitglobe.com
[Sun25 08:51] - Space.py          :256 :j.space              - INFO     - Cloud space ID:1336 name:vmnode size:1 image:1 disksize:17
[Sun25 08:52] - Space.py          :287 :j.space              - INFO     - machine created.
[Sun25 08:53] - PrefabCore.py     :1124:j.prefabcore         - INFO     - RUN:getent passwd | egrep '^root:' ; true
[Sun25 08:53] - ExecutorSSH.py    :63  :j.executor           - INFO     - EXECUTE 10.101.107.158:2200: [ ! -e '/home/cloudscalers/.bash_profile' ] && touch '/home/cloudscalers/.bash_profile' ;source /home/cloudscalers/.bash_profile;getent passwd | egrep '^root:' ; true
[Sun25 08:53] - SSHClient.py      :61  :158:2200(cloudscalers) - INFO     - root:x:0:0:root:/root:/bin/bash
python3: /libssh2-1.8.0/src/channel.c:2466: _libssh2_channel_free: Assertion `session' failed.
Segmentation fault (core dumped)
Aborted 
```
