### ISSUE TITLE
Can't add a user to a certain account (or vdc, ..)

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#77]
## Scenario
1- Run a blueprint to create an account
```
github.com/openvcloud/0-templates/account/0.0.1 - 41ef8d86-a09f-42d3-9819-792525694345 - johnacc33
github.com/openvcloud/0-templates/openvcloud/0.0.1 - 28b96bb5-d554-4942-82ff-1f408838630e - be-g8-3
github.com/openvcloud/0-templates/sshkey/0.0.1 - b4cd10b8-3876-47ab-b91c-910d0019adff - key
github.com/openvcloud/0-templates/vdcuser/0.0.1 - 239b900d-cfcc-4c95-9fc5-1231aa43dc4c - gig_qa_1
github.com/openvcloud/0-templates/vdcuser/0.0.1 - 0ead7e1a-c65c-4b4a-85e8-04641727e2c0 - test98
root@0-robot0:~/blueprints# 

```
2- Run a blueprint to add a user

## Blueprint
```
services:
    - github.com/openvcloud/0-templates/sshkey/0.0.1__key:
        dir: '/root/.ssh/'
        passphrase: 'tesing'
    - github.com/openvcloud/0-templates/openvcloud/0.0.1__be-g8-3:
        address: 'be-g8-3.demo.greenitglobe.com'
        login: 'kheirj@itsyouonline'
        token: '****************'
        location: be-g8-3
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
        openvcloud: be-g8-3
        provider: itsyouonline
        email: dina.magdy.mohammed+123@gmail.com
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__test98:
        openvcloud: be-g8-3
        provider: itsyouonline
        email: test@greenitglobe.com
        groups: ['user']
    - github.com/openvcloud/0-templates/account/0.0.1__johnacc33:
        openvcloud: be-g8-3

actions:
    - template: github.com/openvcloud/0-templates/account/0.0.1
      actions: ['user_add']
      args:
        user:
          name: test98@itsyouonline
          accesstype: R



```

## Error
```
[Sun25 10:34] - base.py           :191 :service-41ef8d86-a09f-42d3-9819-792525694345 - ERROR    - error executing action user_add:
Traceback (most recent call last):
  File "/root/0-robot/zerorobot/task/task.py", line 76, in execute
    self._result = self.func(**self._args)
  File "/opt/code/github/openvcloud/0-templates/templates/account/account.py", line 107, in user_add
    raise ValueError('no account service found with name "%s"', user['name'])
ValueError: ('no account service found with name "%s"', 'test98@itsyouonline')


```
