### ISSUE TITLE
Delete user from cloudspace with user_delete action doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [openvcloud/0-templates#84]
## Steps 
- Add user to created cloudspace .
- Delete this user useing the following blueprint 
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__e8e71aae:
       dir: '/root/.ssh/'
       passphrase: 'e8e71aae'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__f61afa63:
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: '---'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      openvcloud: f61afa63
      provider: itsyouonline

  - github.com/openvcloud/0-templates/account/0.0.1__3e3bebe5:
      openvcloud: 77bccf3a

  - github.com/openvcloud/0-templates/vdc/0.0.1__cdde325b:
      maxMemoryCapacity: 318
      maxNetworkPeerTransfer: 269
      maxDiskCapacity: 249
      maxCPUCapacity: 379
      account: 3e3bebe5
      maxNumPublicIP: 426

actions:
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    args:
      username: 3aa5e83c
    actions: ['user_delete']
    service: cdde325b

```
## Issue 
user still exist on cloudspace with same  access and no error happen through the execution of blueprint
