### ISSUE TITLE
need to format the error of  adding non-existing user to cloudspace 

### ISSUE THREAD

**Issue by Dinaamagdy** [openvcloud/0-templates#97]
## Steps 
-Try to add  non-existing user to cloud space 
## Issue 
the error message need to be formating, as the error now as following 
```
'(\'no vdcuser service found with name "%s"\', \'fa185e6a@itsyouonline\')'

```
## blueprint
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__30bd2d79:
       dir: '/root/.ssh/'
       passphrase: '30bd2d79'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__ecee43be:
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: 
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      email: dina.magdy.mohammed+123@gmail.com
      openvcloud: ecee43be
      provider: itsyouonline

  - github.com/openvcloud/0-templates/account/0.0.1__d68cb7db:
      openvcloud: cc2d8837

  - github.com/openvcloud/0-templates/vdc/0.0.1__4e777c14:
      maxMemoryCapacity: 710
      account: d68cb7db
      maxNumPublicIP: 54
      maxNetworkPeerTransfer: 579
      maxVDiskCapacity: 55
      maxCPUCapacity: 296

actions:
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    service: 4e777c14
    actions: ['user_add']
    args:
      user:
          accesstype: R
          name: ebef30d2@itsyouonline

```
